###ekf config file ###
###this config is for slam###

ekf_local_node:
    ros__parameters:
        
        frequency: 20.0
        
        initial_state: [0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0,
                        0.0, 0.0, 0.0]
                       
        two_d_mode: true
        
        publish_acceleration: true
        
        publish_tf: true
        
        world_frame: odom
        map_frame: map
        odom_frame: odom
        base_link_frame: base_footprint
        
        
        odom0: "/odom_diff"
        odom0_config: [true,  true,  false,   
                      false, false, true,    
                      true, false, false,    
                      false, false, false,    
                      false, false, false]    
                      
                      ###position    ###
                      ###orientation ###
                      ###speed       ###
                      ###angular     ###
                      ###acceleration###
                      
        odom0_differential : true
        odom0_queue_size: 10
                      
        imu0: "/imu"
        
        imu0_remove_gravitational_acceleration: true
        
        imu0_config: [false, false, false,
                     false, false,false,
                     false, false, false,
                     false,  false,  true,
                     true,  true,  false]
                    
        imu0_relative : true
        imu0_queue_size: 10
        
